### ISSUE TITLE
Try to mount S3 with rclone docker

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/data-mounter#8]
From the docker at https://github.com/QCDIS/NaaVRE/blob/datamesh/docker/Dockerfile 
start the container: docker run -it CONTAINER_ID /bin/bash 
and mount S3 from: https://rclone.org/s3/#configuration

**Comment by JustinMingo** [comment]
No luck via the lifewatch. When I launch a terminal it can't find rclone.

Utrecht university has it: https://utrechtuniversity.github.io/research-engineering/manuals/install-rclone/

I get the following errors when I try that (something with privileges?):

jovyan@jupyter-justinmingo:~$ rclone config
bash: rclone: command not found

jovyan@jupyter-justinmingo:~$ curl https://rclone.org/install.sh | sudo bash

sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4669  100  4669    0     0  27427      0 --:--:-- --:--:-- --:--:-- 27627
curl: (23) Failure writing output to destination

jovyan@jupyter-justinmingo:~$ rclone version
bash: rclone: command not found

**Comment by JustinMingo** [comment]
I think it worked:

Current remotes:

Name                 Type
====                 ====
test                 s3
